package Swing_learning.testApp;

import com.jgoodies.forms.layout.CellConstraints;
import com.jgoodies.forms.layout.FormLayout;

import javax.swing.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class testform {
	private JPanel panel1;
	private JList list1;
	private JButton button1;

	private DefaultListModel<String> categories;

	public static void main(String[] args) {
		JFrame frame = new JFrame("testform");
		frame.setContentPane(new testform().panel1);
		frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
		frame.pack();
		frame.setVisible(true);
	}

	private void createUIComponents() {

		panel1 = new JPanel();
		categories = new DefaultListModel();
		categories.addElement("test");

		ListenForButton lForButton = new ListenForButton();

		button1 = new JButton();
		button1.addActionListener(lForButton);

		list1 = new JList(categories);
	}

	{
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
		$$$setupUI$$$();
	}

	/**
	 * Method generated by IntelliJ IDEA GUI Designer
	 * >>> IMPORTANT!! <<<
	 * DO NOT edit this method OR call it in your code!
	 *
	 * @noinspection ALL
	 */
	private void $$$setupUI$$$() {
		createUIComponents();
		panel1 = new JPanel();
		panel1.setLayout(new FormLayout("fill:200px:noGrow", "center:200px:noGrow,top:4dlu:noGrow,center:max(d;4px):noGrow"));
		final JScrollPane scrollPane1 = new JScrollPane();
		CellConstraints cc = new CellConstraints();
		panel1.add(scrollPane1, cc.xy(1, 1, CellConstraints.FILL, CellConstraints.FILL));
		scrollPane1.setViewportView(list1);
		button1.setText("Button");
		panel1.add(button1, cc.xy(1, 3));
	}

	/**
	 * @noinspection ALL
	 */
	public JComponent $$$getRootComponent$$$() {
		return panel1;
	}


	private class ListenForButton implements ActionListener {

		@Override
		public void actionPerformed(ActionEvent e) {

			if (e.getSource() == button1) {
				categories.removeAllElements();

				categories.addElement("test2");
			}
		}
	}
}
